@Restaurants.Api_HostAddress = http://localhost:7168
@token =hefffffffff


GET {{Restaurants.Api_HostAddress}}/api/restaurants
Authentication: Bearer {{token}}

Accept: application/json

###
GET {{Restaurants.Api_HostAddress}}/api/restaurants/2
Accept: application/json

###

POST {{Restaurants.Api_HostAddress}}/api/identity/register
Contant-Type: application/json

{
  "email" : "admin@test.com",
  "password" : "Admin123*"


}
###

POST {{Restaurants.Api_HostAddress}}/api/identity/login
Contant-Type: application/json

{
  "email" : "admin@test.com",
  "password" : "Admin123*"


}